### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by JustineEvansUM** [Media-Ed-Online/intro-web-dev#1]
This is a test issue for this Issues Board. Replies are disabled. 

Example HW Post

# Intro-01: GitHub Pt. 1

_[Project 1: Your Homework Environment](https://github.com/Media-Ed-Online/intro-web-dev/projects/7) is broken up into 2 topics/weeks:_
- [x] Intro-01 **Deadline: 9/10 @ 11:55PM**
- [ ] Intro-02 **Deadline: 9/17 @ 11:55PM**

Please create a ![Comment](http://fourjobfiesta.com/img/offline.png) to this issue (**not** a New Issue) below, responding to this prompt:

> Go through the Topic 1 materials from our course website on the internet. What are your thoughts? Were you surprised by anything? What are your expectations on this class?

For Pt 2, should they edit their replies? Create a new comment? Get them to do it first?

To link to your repos and sites, please use this markdown formula:
`[P1 Repo](https://github.com/user/repo-name), [Live Site](https://user.github.io/repo-name/)`

For example...
`[P1 Repo](https://github.com/JustineEvansUM/341-Work), [Live Site](https://justineevansum.github.io/341-work/)`

...which will render like this:
[P1 Repo](https://github.com/JustineEvansUM/341-Work), [Live Site](https://justineevansum.github.io/341-work/)

**Comment by justinenevans** [comment]
Test reply.

**Comment by justinenevans** [comment]
Test reply.

**Comment by justinenevans** [comment]
[test reply 3](https://www.google.com)

**Comment by JustineEvansUM** [comment]
test reply 4

**Comment by justinenevans** [comment]
test 5

**Comment by JustineEvansUM** [comment]
test 6
