### ISSUE TITLE
Group A Submission - Project 1

### ISSUE THREAD

**Issue by rachelhofer18** [Media-Ed-Online/intro-web-dev#29]
[P1 Repo](https://github.com/rachelhofer18/Project-1), [Live Site](file:///Users/RachelHofer/Documents/Rachel%20Hofer/Homework/Web%20Dev%20-%20Homwork/Project%201/index.html)

**Comment by jacelynhenderson** [comment]
https://github.com/jacelynhenderson/README.md/blob/master/README.md
