### ISSUE TITLE
Project 2 submission?

### ISSUE THREAD

**Issue by MistyDaniels** [Media-Ed-Online/intro-web-dev#47]
Do we need to put our project 2 stuff on github yet, or should I just continue working on it till later? I know its not complete since we're still going through, was just curious.

**Comment by JustineEvansUM** [comment]
Hi, @MistyDaniels. You should push your work and turn in what you have. In this case, it's the link to your Project-2 repo, and the `index.html` you've been working on.

You will continue working in your P2 repo for the next several weeks. We'll just look at different pages as we go along!

**Comment by MistyDaniels** [comment]
Alright, I'll make sure to push it when I get off work tonight. Thank you!
