### ISSUE TITLE
Help! Text not showing up how I expected

### ISSUE THREAD

**Issue by Dakota-Wharry123** [Media-Ed-Online/intro-web-dev#49]
![screen shot 2017-09-25 at 3 52 38 pm](https://user-images.githubusercontent.com/31643143/30832789-b3194860-a209-11e7-9434-b4263ec836f3.png)
![screen shot 2017-09-25 at 3 52 05 pm](https://user-images.githubusercontent.com/31643143/30832790-b508df1e-a209-11e7-8b1a-f9ff91f57696.png)
Why is the text at the bottom showing up in all bold rather than just the things I indicated in the syntax? Also, why is it stair stepping off to the right as it gets further down? I tried to add the <br /> syntax hoping that would prevent the stair stepping, but as you can see it didn't. 
Any Suggestions?
@JustineEvansUM 
@JeramyMT 
@JonSwallow

**Comment by JonSwallow** [comment]
@Dakota-Wharry123 line 43 /ol. I ran the second part in my atom concerning your strong text and could not reproduce the error so it has to be above that point in the code. Close that ordered list and it may solve all of it. It will surely fix the stair stepping. Sorry I could not be of more help.

**Comment by FriedmanM** [comment]
Ohhhh. on line 37 you didn't close the ```<ul>``` tag. You need to change it to ```</ul>```

**Comment by Dakota-Wharry123** [comment]
Thanks Guys!
I owe you one.
