### ISSUE TITLE
Homework due Oct. 9

### ISSUE THREAD

**Issue by MarkLannenUM** [Media-Ed-Online/intro-web-dev#55]

**Comment by MarkLannenUM** [comment]
Can anyone point me to information on the assignment due next Monday, Oct. 9? I've gotten a bit turned around and am not really clear on what I should be doing.  Thanks!

**Comment by JonSwallow** [comment]
@MarkLannenUM I noticed the website is not yet up for the week, hopefully soon. That is probably where it will be, a continuance on the same project. Cheers!

**Comment by MistyDaniels** [comment]
I think Justine is still dealing with her health, but it'll hopefully be up soon.

**Comment by JustineEvansUM** [comment]
Hey, team!

Golly, I hope everyone's seeing it now... I'm back to the office, so let me know if this Titanic is sinking!

**Comment by MarkLannenUM** [comment]
I see it - thanks Justine!
