### ISSUE TITLE
Images Not Showing Up 

### ISSUE THREAD

**Issue by sUMmermixon** [Media-Ed-Online/intro-web-dev#60]
Literally none of my images will show up on the live site or in my README. 😭
They show up when I have Preview toggled while coding.... 
Not sure what I'm doing wrong. 
No errors pop up while coding either. 😳
The titles show up though? What is happening. 

`<img src="/Users/summixalot/Desktop/ss.png" alt="screenshot" title="screenshot" />`

`<img src="/Users/summixalot/Documents/Homework/web-dev-hw/Project2/images/cream.jpg" alt="step 1, creaming together butter and sugar" title="creaming together butter and sugar" width="600" height="400"/>`

**Comment by JonSwallow** [comment]
@sUMmermixon  ../images try that.

**Comment by JustineEvansUM** [comment]
Hi, Summer; 

You're giving the location to your files from your local drive - no one on the net could see it without being on a direct network to your machine. Thank goodness!

Try `../images/cream.jpg` instead of that full string.

**Comment by sUMmermixon** [comment]
ohhhhhhhh, thank you guys!

**Comment by JonSwallow** [comment]
@sUMmermixon  double check your page, I went to see your images and the link to home (ingredients) is broken. Remember the others are in /pages/  the original is outside that  folder so the link will be different.
