### ISSUE TITLE
Form Heading

### ISSUE THREAD

**Issue by nboose** [Media-Ed-Online/intro-web-dev#66]
Do I still need to do a heading for my form, similar to the heading we did for all of our other documents? For example.  .  .

![snapshot](https://user-images.githubusercontent.com/31861762/31477898-8b04e136-aeca-11e7-8cd5-2672b531c199.PNG)

If so, where do I put <form action. . .

**Comment by JonSwallow** [comment]
@nboose It helps. There were some requirements for the heading in the material. I used the same style as I did for my Index.html so they would match.
