### ISSUE TITLE
Title font changes between pages

### ISSUE THREAD

**Issue by mjohnson92** [Media-Ed-Online/intro-web-dev#94]
My title font changes between index.html and the rest of the about, contact, and sample pages. It becomes a little smaller and the font even changes like a chain is being broken. Can't figure this out and have spent a while on it! Would love a few opinions!

The title also links back as a home page, maybe thats why it changes?

Heres my folders..
https://github.com/mjohnson92/web-dev-hw/tree/master/project-03

**Comment by MistyDaniels** [comment]
It looks like its not linked properly
"    <link rel="stylesheet" href="./css/fonts.css">
    <link rel="stylesheet" type="text/css" href="../css/style.css">"
is what you have, and I think it should be:
<link rel="stylesheet" href="../css/fonts.css">

**Comment by mjohnson92** [comment]
I thought that might of been it but it just removes the css altogether when i change directories. It was working for a while when everything was the same font but now that I'm using a new one it is creating this problem. Maybe i'll try messing with different fonts.

**Comment by mjohnson92** [comment]
<img width="1265" alt="screen shot 2017-11-05 at 12 03 49 pm" src="https://user-images.githubusercontent.com/31572980/32418138-7e3ad252-c221-11e7-99b5-8575e5dc7a3d.png">
<img width="1257" alt="screen shot 2017-11-05 at 12 03 59 pm" src="https://user-images.githubusercontent.com/31572980/32418139-7e5359a8-c221-11e7-87be-26054899c1ba.png">

**Comment by mjohnson92** [comment]
<img width="1258" alt="screen shot 2017-11-05 at 12 05 09 pm" src="https://user-images.githubusercontent.com/31572980/32418149-9a62f284-c221-11e7-992a-1e87ac06fc46.png">
<img width="1257" alt="screen shot 2017-11-05 at 12 03 59 pm" src="https://user-images.githubusercontent.com/31572980/32418151-9c5c8fb4-c221-11e7-9b50-b895f0e65ec0.png">

**Comment by mjohnson92** [comment]
oh wow you were right i was just changing the style page directory and not the font page directory!!
